all:
  children:

    app:
      hosts:
        app1:
          ansible_host: 192.168.56.10
        app2:
          ansible_host: 192.168.56.11

    db_servers:
      hosts:
        db:
          ansible_host: 192.168.56.20

    lb_servers:
      hosts:
        lb:
          ansible_host: 192.168.56.30

    ci_servers:
      hosts:
        jenkins:
          ansible_host: 192.168.56.40

    nexus_servers:
      hosts:
        nexus:
          ansible_host: 192.168.56.60

    sonar_servers:
      hosts:
        sonar:
          ansible_host: 192.168.56.50

    redis_servers:
      hosts:
        redis:
          ansible_host: 192.168.56.21

    monitoring_servers:
      hosts:
        monitoring:
          ansible_host: 192.168.56.99